spring.application.name=journalApp

spring.data.mongodb.auto-index-creation=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhprashant8130@gmail.com
spring.mail.password=dwax jilu xoni atbw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true